# Generated by Django 3.0.7 on 2020-07-07 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0002_auto_20200707_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 17, 55, 23, 160279, tzinfo=utc)),
        ),
    ]
