# Generated by Django 3.0.8 on 2020-08-05 04:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0004_auto_20200712_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 4, 27, 37, 349780, tzinfo=utc)),
        ),
    ]
