# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-05 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0006_auto_20200805_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 4, 54, 21, 963520, tzinfo=utc)),
        ),
    ]
